name: wan_android
description: A meeting application use flutter

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # State
  provider: ^3.0.0+1

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter : ^0.3.10+4
  device_info: ^0.4.0+1
  package_info: ^0.4.0+3
  #  connectivity: ^0.4.3+6

  # Data
  json_annotation: ^2.4.0
  dio: ^2.1.13
  cookie_jar: ^1.0.0
  shared_preferences: ^0.5.2+2
  html_unescape: ^1.0.1+3
  flutter_html: ^0.10.4

  # io
  #  common_utils: ^1.1.1
  crypto: ^2.0.6

  # UI
  oktoast: ^2.1.7
  pull_to_refresh: ^1.5.0
  flutter_swiper: ^1.1.6
  cached_network_image: ^1.1.1

  # third
  url_launcher: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#  build_runner: ^1.6.2
#  json_serializable: ^3.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

  assets:
    - assets/images/

